[project]
name = "deepwaters"
version = "0.1.0"
authors = [
  { name="Luis Quentin Gentner", email="luis.gentner@outlook.com" },
]
description = "Reconstructing Pre-GRACE Terrestrial Water Storage Anomalies Using Deep Learning"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "cartopy>=0.24.1",
    "cdsapi>=0.7.4",
    "cf-xarray>=0.10.0",
    "dask>=2024.11.1",
    "geopandas>=1.0.1",
    "isimip-client>=1.0.1",
    "lightning>=2.4.0",
    "matplotlib>=3.9.2",
    "omegaconf>=2.3.0",
    "pyjanitor>=0.29.2",
    "regionmask>=0.12.1",
    "rioxarray>=0.18.1",
    "ruamel-yaml>=0.18.6",
    "scikit-learn>=1.5.2",
    "seaborn>=0.13.2",
    "tabulate>=0.9.0",
    "torch>=2.5.1",
    "torchinfo>=1.8.0",
    "tqdm>=4.67.0",
    "wandb>=0.18.6",
    "xarray>=2024.10.0",
    "xskillscore>=0.0.26",
    "zarr>=2.18.3",
]
