scenario: Val22-23_ERA
trainer:
  default_root_dir: models/trained/global
  max_epochs: 20
  accelerator: gpu
  sync_batchnorm: True
  gradient_clip_val: 1.0
  val_check_interval: 0.5
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      save_dir: ${trainer.default_root_dir}/logs
      project: deeprec-paper_ensembles
      log_model: all
  callbacks:
    - class_path: lightning.pytorch.callbacks.LearningRateMonitor
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        dirpath: "${trainer.default_root_dir}/checkpoints"
        save_top_k: -1
        save_on_train_epoch_end: false
        filename: "deeprec-{epoch:02d}-{val_loss:.2f}"
    - class_path: lightning.pytorch.callbacks.RichModelSummary
      init_args:
        max_depth: -1

optimizer:
  class_path: torch.optim.Adam
  init_args:
    lr: 8e-5

lr_scheduler:
  class_path: torch.optim.lr_scheduler.CosineAnnealingLR
  init_args:
    eta_min: 1e-7
    T_max: ${trainer.max_epochs}

model:
  class_path: deeprec.models.rnn.CropResNetLSTM
  init_args:
    weight_lat: true
    loss: nll_laplace
    cnn_channels: [32, 48, 72, 108]
    rnn_layers: 1
    rnn_hidden_size: 128
    rnn_dropout: 0.0
    # Linked variables
    n_tensor_inps: ${len:${data.tensor_input_vars}}
    n_matrix_inps: ${len:${data.matrix_input_vars}}
    n_vector_inps: ${len:${data.vector_input_vars}}

data:
  data_dir: data/processed
  val_split:
  - 2022-01-01
  - 2023-12-01
  train_split:
  - 2002-04-01
  - 2021-12-01
  #----------------
  scale_method: robust
  coverage:
    data_vars:
    - land_mask_jpl
    - land_mask_gsfc
    - grl_ata_mask
  target_var: twsa_csr
  tensor_input_vars:
  - era5_d2m
  - era5_t2m
  - era5_e
  - era5_lai_hv
  - era5_lai_lv
  - era5_pev
  - era5_sro
  - era5_ssro
  - era5_sp
  - era5_tp
  - era5_swvl1
  - era5_swvl2
  - era5_swvl3
  - era5_swvl4
  matrix_input_vars:
  - nvec_x
  - nvec_y
  - nvec_z
  - cell_area
  - cropland_irrigated
  - cropland_rainfed
  - pastures
  - urbanareas
  - lakes
  vector_input_vars:
  - year_sin
  - year_cos
  - year2_sin
  - year2_cos
  - oni
  space_window: 35
  time_window: 13
  batch_size: 256
  num_workers: 6
  persistent_workers: true